export const mapAccountHolderData = (profileHolder, summary, extraFields = {}) => {
  if (!profileHolder && !summary) return null;
  const { name, email, dob, landLine, address, ckycCompliance, mobile, pan, nominee } =
    profileHolder || {};
  const {
    pending = {},
    currentODLimit,
    openingDate,
    branch,
    currentBalance,
    drawingLimit,
    status,
    micrCode,
    balanceDateTime,
    currency,
    ifscCode,
    type,
    facility,
    exchgeRate,
  } = summary || {};
  return {
    name: name || '',
    email: email || '',
    dob: dob ? new Date(dob).toISOString().split('T')[0] : '',
    landline: landLine || '',
    address: address || '',
    ckycCompliance: ckycCompliance || '',
    mobile: mobile || '',
    pan: pan || '',
    nominee: nominee || '',
    holderType: extraFields?.holderType || '',
    pendingTransactionType: pending.transactionType || '',
    pendingAmount: pending.amount !== undefined ? String(pending.amount) : '',
    currentODLimit: currentODLimit || '',
    openingDate: openingDate || '',
    branch: branch || '',
    currentBalance: currentBalance || '',
    drawingLimit: drawingLimit || '',
    status: status || '',
    micrCode: micrCode || '',
    balanceDateTime: balanceDateTime ? new Date(balanceDateTime).toISOString() : '',
    currency: currency || '',
    ifscCode: ifscCode || '',
    accountType: type || '',
    facility: facility || '',
    exchgeRate: exchgeRate || '',
    requestId: extraFields.requestId || '',
    userId: extraFields.userId || '',
    linkedAccRef: extraFields.linkedAccRef || '',
    maskedAccNumber: extraFields.maskedAccNumber || '',
  };
};

export const preparePayloadForEsign = (
  pdf,
  contractName,
  contractExecuterName,
  successRedirectUrl,
  failureRedirectUrl,
  contractTtl,
  signerName,
  signerGender,
  uid,
  pincode,
  signerYearOfBirth,
  signerUniqueId,
  pageNo,
  signaturePosition,
  signerCallbackUrl,
  signerCallbackUrlAuthorizationHeader,
) => {
  return {
    pdf,
    contractName,
    contractExecuterName,
    successRedirectUrl,
    failureRedirectUrl,
    contractTtl,
    signerCallbackUrl,
    signerCallbackUrlAuthorizationHeader,
    signerdetail: [
      {
        signerName,
        signerGender,
        uidLastFourDigits: uid?.slice(-4),
        pincode,
        signerYearOfBirth,
        signerUniqueId,
        signatureType: 'AADHAARESIGN-OTP',
        signatures: [{ pageNo: [pageNo], signaturePosition: [signaturePosition] }],
      },
    ],
  };
};
